---
title: "Research"
---

My current research focuses on the relationship between environmental enforcement and state building, with a regional emphasis in Latin America. I also have ongoing interests in bureaucratic politics, causal inference, and state-society relations in frontier regions. In the past I've also worked on topics related to direct democracy and citizenship.

## Working papers

**Eyes beneath the canopy: co-enforcing environmental crackdowns in the Brazilian Amazon**. Latest version: May 12, 2023.

> **Abstract**: How do state-society relations affect law enforcement crackdowns? I propose that in contexts of administrative constraints, sharp increases in state resources will be most effective wherever we find synergetic dynamics between enforcement officials and local groups. I argue that this pattern is the result of the two actors engaging in the "co-production" of law enforcement, where state agents provide technical expertise while communities offer their deep knowledge of the terrain. I test this theory by examining anti-deforestation policies in the Brazilian Amazon. Exploiting the assignment of municipalities into the Lista de Municípios Prioritários---a blacklist intended to curb clearings---through a combination of triple-difference and extended two-way fixed effects models I show that while the LMP crackdown led to significant forest cover retention within indigenous lands, its effects outside of them were mixed. I claim that this pattern is the result of uneven shifts in the perceived costs of illegal activity, which I support by showing that the crackdown-led increase in the enforcement rate is shaped by indigenous presence, and that in turn this affects future criminal behavior. Consequently, this paper stresses how good policy outcomes can only be achieved through a combination of formal provision and local support.

## Published

[Two paths towards the exceptional extension of national voting rights to non-citizen residents](https://www.tandfonline.com/doi/full/10.1080/1369183X.2023.2182713). (2023). with David Altman and Sergio Huertas-Hernández. *Journal of Ethnic and Migration Studies*, 49(*10*), pp. 2541-2560. DOI: 10.1080/1369183X.2023.2182713

> **Abstract**: Only five countries have extended universal voting rights to non-citizen residents for all political spheres (local, intermediate and national): Uruguay in 1934, New Zealand in 1975, Chile in 1980, Malawi in 1994, and Ecuador in 2008. These cases constitute a unique intercontinental medley and an opportunity to study the conditions behind such revolutionary change. Through a calibrated comparative strategy based on most similar system designs (inspired by Mill’s method of difference) using QCA, this paper finds that the extension of national voting rights to non-citizen residents transpired in two distinct scenarios. The first setting (Chile, New Zealand, and Uruguay) took place within unitary states with already-existing local voting rights for non-citizen residents and settler trajectories, but that were not undergoing a liberalisation process. On the other hand, the second configuration (Ecuador and Malawi) developed within unitary states that recognised nationality by *ius soli* and were going through a process of liberalisation, but without previous local voting rights for non-citizen residents or a settler trajectory. To our best knowledge, this paper offers the first cross-national explanation that involves all cases that have broadened their respective political communities (*demoi*) to include national voting rights to all non-citizen residents.

[Citizens at the polls: direct democracy in the world, 2020](https://www.tfd.org.tw/en/publication/journal). (2021). with David Altman. *Taiwan Journal of Democracy*, 17(*2*), pp. 85-106.

> **Abstract**: There is suggestive evidence that the growth of democracy has stagnated, and even some signs indicate that democracy is in retreat. In such a context, one might have expected to witness an increase in experimentation with democratic innovations such as direct democracy. This is not the case. While there is a spectacular and statistically significant increase in the uses of mechanisms of direct democracy (MDDs) since the early 1990s, 2020 remained notably similar to the previous years in terms of the level of direct democracy worldwide. In 2019, we witnessed less than half of the MDDs we saw in 2018 (eighteen vs. fifty), but, in 2020, the count bounced back to thirty. The COVID-19 pandemic did not halt the march of direct democracy, although it delayed some of its events. Beyond the specific number of popular votes in 2020, direct democracy still tracks almost perfectly with global electoral democracy trends. When all was said and done, however, thirty MDDs were held in 2020: fourteen obligatory referendums (eight in Liberia, two in Chile, and one in Algeria, Italy, Palau, and Northern Cyprus, respectively), six plebiscites (two in New Zealand, two in Liechtenstein, one in Russia, and one in Guinea), five popular initiatives (four in Switzerland and one in Liechtenstein), and five rejective referendums (all in Switzerland).
