---
title: "Teaching"
---

I've been a Teaching Assistant in both graduate and undergraduate courses, with a focus on comparative politics and research design. I am also in the process of obtaining an [MIT Teaching Certificate](https://tll.mit.edu/programming/grad-student-programming/teaching-certificate-pathways/).


## Massachusetts Institute of Technology (MIT)

*Quantitative Research Methods II: Causal Inference*

- Instructor of record: F. Daniel Hidalgo
- Semester: Spring 2024 (ongoing)
- Level: graduate

*Political Science Scope and Methods*

- Instructor of record: Fotini Christia
- Semester: Fall 2023
- Level: undergraduate
- Teaching evaluations: 6.9 out of 7


## Pontifical Catholic University of Chile (PUC-Chile)

2019

- Introduction to Political Science (Carla Alberti)
- Indigenous Politics In Latin America (Carla Alberti)
- Political Processes in Latin America (Valeria Palanza)

2018

- Introduction to Political Science (Carla Alberti)
- Introduction to Comparative Politics (Julieta Suárez-Cao)
- Qualitative Research Methods in Political Science (Julieta Suárez-Cao)
- Writing in Political Science (Maria de la Calle)

2017

- Writing in Political Science (Maria de la Calle)
